### ISSUE TITLE
"node-wifi-mqtt" fails to compile

### ISSUE THREAD

**Issue by thehi1** [hiveeyes/arduino#32]
I am also trying to compile the file `node-wifi-mqtt.ino`. The following message appears when compiling (I am using the Arduino IDE 1.8.13):
```
exit status 1
'SerialDebug' was not declared in this scope
```
What could be the cause?

Using atom I get the message: 
```
C:/ XXXX PlatformIO/Projects/210502-191434-d1_mini_pro/src/node-wifi-mqtt.ino:955:5: error: 'SerialDebug' was not declared in this scope
     SerialDebug.debug(INFO, "mqtt_connect", "Connecting to MQTT broker");
```

Thanks in advance

**Comment by amotl** [comment]
Hi @thehi1,

thank you for writing in.

> 'SerialDebug' was not declared in this scope

Can you look on the Arduino Library Manager for a corresponding library? It is https://playground.arduino.cc/Code/SerialDebugger/, actually.

With kind regards,
Andreas.

**Comment by amotl** [comment]
You can also get all of the libraries used within the programs into the `libraries` folder by invoking:
```
git submodule update --init --recursive
```

**Comment by amotl** [comment]
Hi @thehi1,

#33 will now use a different SerialDebug library. Because the `SerialDebugger` by Arduino referenced above seemed very much outdated, we switched over to another library by Joao Lopes which seems to be amongst the most popular ones when searching on PlatformIO [1].

Please let us know if that actually works. At least, it compiles without errors on my machine when invoking `make`.

With kind regards,
Andreas.

[1] https://platformio.org/lib/search?query=serialdebug
